version: 2

updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: build
    rebase-strategy: auto

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
    rebase-strategy: auto

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: build
    rebase-strategy: auto
